---
title: "Cameron Peak Fire - Precipitation and Snowmelt Frequency Analysis"
author: "MGS"
date: "8/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Download all libraries used in the script.

```{r}
library(RNRCS) # pull SNOTEL data
library(lubridate) # fix date
library(dplyr) # data manipulation
library(weathermetrics) # F to C conversion
library(knitr) #knit the data
library(ggplot2) # plot data
```

In this code block, the data is being downloaded from the NRCS website, put into proper units, and columns are being added for hourly precip, SWE, and snow depth (not cumulative). 

```{r}
#download Joe Wright SNOTEL data from WY 2010 to present and add as a df. Also, get date into correct format.
JWhourly_SNO <- grabNRCS.data(network = "SNTL", site_id = 551, timescale = "hourly", DayBgn = '2009-10-01', DayEnd = '2020-08-27') %>%
  mutate(Date = ymd_hm(Date))

#get into correct units and make sure the new columns are numeric (except date)
JWhourly_SNO$AirTemp_C <- fahrenheit.to.celsius(JWhourly_SNO$Air.Temperature.Observed..degF.)
JWhourly_SNO$CumSWE_mm <- JWhourly_SNO$Snow.Water.Equivalent..in.*25.4
JWhourly_SNO$CumSnowDepth_mm<-JWhourly_SNO$Snow.Depth..in.*25.4
JWhourly_SNO$CumPrecip_mm<-JWhourly_SNO$Precipitation.Accumulation..in. *25.4
JWhourly_SNO[2:9] <- lapply(JWhourly_SNO[2:9], as.numeric)

#create new df that has all the proper units from above
JW_hourly <- JWhourly_SNO[c(1,6:9)]

#remove negative values
JW_hourly <- JW_hourly %>%
  filter(CumSWE_mm >= 0, CumPrecip_mm >= 0, CumSnowDepth_mm >= 0)

#Add columns to get hourly data instead of cumulative 
JW_hourly %>%
  mutate(Precip_mm = CumPrecip_mm - lag(CumPrecip_mm), 
         SnowDepth_mm = CumSnowDepth_mm - lag(CumSnowDepth_mm), 
         SWE_mm = CumSWE_mm - lag(CumSWE_mm))

JW_hourly$Precip_mm <- ave(JW_hourly$CumPrecip_mm, FUN=function(x) c(0, diff(x)))
JW_hourly$SnowDepth_mm <- ave(JW_hourly$CumSnowDepth_mm, FUN=function(x) c(0, diff(x)))
JW_hourly$SWE_mm <- ave(JW_hourly$CumSWE_mm, FUN=function(x) c(0, diff(x)))

#determine NAs in 10 yr dataset
sum(is.na(JW_hourly$SWE_mm))
sum(is.na(JW_hourly$Precip_mm))
sum(is.na(JW_hourly$SnowDepth_mm))

```

The following blode of code is to determine if the precip is rain or snow. If SWE is 0 mm, the precip is rain and if it is greater than 0 mm it is snow.

```{r}

ifelse(JW_hourly$SWE_mm > 0, JW_hourly$SnoPrecip_mm <- JW_hourly$Precip_mm, JW_hourly$Rain_mm <- JW_hourly$Precip_mm)


ggplot(JW_hourly, aes(x=Date, y=Rain_mm)) + geom_line ()

```

